
exports.matchdates = [
    {
        matchday    : '1',
        team1       : 'Liverpool',
        score1      : '4',
        score2      : '3', 
        team2       : "Leeds",
        date        : "September 12, 2020 - Saturday",
    },
    {
        matchday    : '2',
        team1       : 'Chelsea',
        score1      : '0',
        score2      : '2', 
        team2       : "Liverpool",
        date        : "September 20, 2020 - Sunday",
    },
    {
        matchday    : '3',
        team1       : 'Liverpool',
        score1      : '3',
        score2      : '1', 
        team2       : "Arsenal",
        date        : "September 28, 2020 - Monday",
    },
    {
        matchday    : '4',
        team1       : 'Aston Villa',
        score1      : '7',
        score2      : '2', 
        team2       : "Liverpool",
        date        : "October 4, 2020 - Sunday",
    },
    {
        matchday    : '5',
        team1       : 'Everton',
        score1      : '2',
        score2      : '2', 
        team2       : "Liverpool",
        date        : "October 17, 2020 - Saturday",
    },
    {
        matchday    : '6',
        team1       : 'Liverpool',
        score1      : '2',
        score2      : '1', 
        team2       : "Sheffield United",
        date        : "October 24, 2020 - Saturday",
    },
    {
        matchday    : '7',
        team1       : 'Liverpool',
        score1      : '2',
        score2      : '1', 
        team2       : "West Ham United",
        date        : "October 31, 2020 - Saturday",
    },
    {
        matchday    : '8',
        team1       : 'Manchester City',
        score1      : '1',
        score2      : '1', 
        team2       : "Liverpool",
        date        : "November 8, 2020 - Sunday",
    },
    {
        matchday    : '9',
        team1       : 'Liverpool',
        score1      : '3',
        score2      : '0', 
        team2       : "Leicester City",
        date        : "November 22, 2020 - Sunday",
    },
    {
        matchday    : '10',
        team1       : 'Brighton',
        score1      : '1',
        score2      : '1', 
        team2       : "Liverpool",
        date        : "November 28, 2020 - Saturday",
    },
    {
        matchday    : '11',
        team1       : 'Liverpool',
        score1      : '4',
        score2      : '0', 
        team2       : "Wolves",
        date        : "December 6, 2020 - Sunday",
    },
    {
        matchday    : '12',
        team1       : 'Fulham',
        score1      : '1',
        score2      : '1', 
        team2       : "Liverpool",
        date        : "December 13, 2020 - Sunday",
    },
    {
        matchday    : '13',
        team1       : 'Liverpool',
        score1      : '2',
        score2      : '1', 
        team2       : "Tottenham Hotspurs",
        date        : "December 16, 2020 - Wednesday",
    },
    {
        matchday    : '14',
        team1       : 'Crystal Palace',
        score1      : '0',
        score2      : '7', 
        team2       : "Liverpool",
        date        : "December 19, 2020 - Saturday",
    },
    {
        matchday    : '15',
        team1       : 'Liverpool',
        score1      : '1',
        score2      : '1', 
        team2       : "West Brom",
        date        : "December 27, 2020 - Sunday",
    },
    {
        matchday    : '16',
        team1       : 'Newcastle United',
        score1      : '0',
        score2      : '0', 
        team2       : "Liverpool",
        date        : "December 30, 2020 - Wednesday",
    },
    {
        matchday    : '17',
        team1       : 'Southampton',
        score1      : '1',
        score2      : '0', 
        team2       : "Liverpool",
        date        : "January 4, 2021 - Monday",
    },
    {
        matchday    : '18',
        team1       : 'Liverpool',
        score1      : '0',
        score2      : '0', 
        team2       : "Manchester United",
        date        : "January 17, 2021 - Sunday",
    },
    {
        matchday    : '19',
        team1       : 'Liverpool',
        score1      : '0',
        score2      : '1', 
        team2       : "Burnley",
        date        : "January 21, 2021 - Thursday",
    },
    {
        matchday    : '20',
        team1       : 'Tottenham Hotspurs',
        score1      : '1',
        score2      : '3', 
        team2       : "Liverpool",
        date        : "January 28, 2021 - Thursday",
    },
    {
        matchday    : '21',
        team1       : 'West Ham',
        score1      : '1',
        score2      : '3', 
        team2       : "Liverpool",
        date        : "January 31, 2021 - Sunday",
    },
    {
        matchday    : '22',
        team1       : 'Liverpool',
        score1      : '0',
        score2      : '1', 
        team2       : "Brighton",
        date        : "February 3, 2021 - Wednesday",
    },
    {
        matchday    : '23',
        team1       : 'Liverpool',
        score1      : '1',
        score2      : '4', 
        team2       : "Manchester City",
        date        : "February 7, 2021 - Sunday",
    },
    {
        matchday    : '24',
        team1       : 'Leicester City',
        score1      : '3',
        score2      : '1', 
        team2       : "Liverpool",
        date        : "February 13, 2021 - Saturday",
    },
    {
        matchday    : '25',
        team1       : 'Liverpool',
        score1      : '0',
        score2      : '2', 
        team2       : "Everton",
        date        : "February 20, 2021 - Saturday",
    },
    {
        matchday    : '26',
        team1       : 'Sheffield United',
        score1      : '0',
        score2      : '2', 
        team2       : "Liverpool",
        date        : "February 28, 2021 - Sunday",
    },
    {
        matchday    : '27',
        team1       : 'Liverpool',
        score1      : '0',
        score2      : '1', 
        team2       : "Chelsea",
        date        : "March 4, 2021 - Thursday",
    },
    {
        matchday    : '28',
        team1       : 'Liverpool',
        score1      : '0',
        score2      : '1', 
        team2       : "Fulham",
        date        : "March 7, 2021 - Sunday",
    },
    {
        matchday    : '29',
        team1       : 'Wolves',
        score1      : '0',
        score2      : '1', 
        team2       : "Liverpool",
        date        : "March 15, 2021 - Monday",
    },
];